// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution state for an agent mailbox action.
 */
export type AgentMailboxActionStatus = "inProgress" | "succeeded" | "failed";
