// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMailboxMessageCategory } from "./AgentMailboxMessageCategory";
import type { AgentMailboxMessagePreview } from "./AgentMailboxMessagePreview";

/**
 * The mailbox operation represented by an action item.
 */
export type AgentMailboxActionKind = { "type": "send", target: string, recipient: string | null, category: AgentMailboxMessageCategory, preview: string | null, } | { "type": "read", sender: string | null, category: AgentMailboxMessageCategory | null, limit: number, messages: Array<AgentMailboxMessagePreview>, };
