// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMailboxActionKind } from "./AgentMailboxActionKind";
import type { AgentMailboxActionStatus } from "./AgentMailboxActionStatus";

/**
 * A visible action performed through the durable agent mailbox.
 */
export type AgentMailboxAction = { id: string, status: AgentMailboxActionStatus, action: AgentMailboxActionKind, };
