// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Safe content projection for a mailbox message.
 */
export type AgentMailboxMessagePreviewContent = { "type": "plaintext", preview: string | null, } | { "type": "encrypted" };
