// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMailboxMessageCategory } from "./AgentMailboxMessageCategory";
import type { AgentMailboxMessagePreviewContent } from "./AgentMailboxMessagePreviewContent";

/**
 * A mailbox message summary exposed by a read action.
 */
export type AgentMailboxMessagePreview = { sender: string, category: AgentMailboxMessageCategory, content: AgentMailboxMessagePreviewContent, };
