// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ConfiguredPromptHookFilter } from "./ConfiguredPromptHookFilter";

export type ConfiguredHookHandler = { "type": "command", command: string, commandWindows: string | null, timeoutSec: bigint | null, async: boolean, statusMessage: string | null, } | { "type": "prompt", prompt: string, model: string | null, filter: ConfiguredPromptHookFilter | null, reasoningEffort: ReasoningEffort | null, timeoutSec: bigint | null, failClosed: boolean, statusMessage: string | null, } | { "type": "agent", };
