// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryMutationAction } from "./MemoryMutationAction";
import type { MemoryMutationScope } from "./MemoryMutationScope";
import type { MemoryMutationStatus } from "./MemoryMutationStatus";

export type MemoryMutation = { id: string, action: MemoryMutationAction, scope: MemoryMutationScope, status: MemoryMutationStatus, title: string | null, path: string | null, preview: string | null, };
