// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnOutputThroughputUpdatedNotification = { threadId: string, turnId: string, active: boolean, outputTokens: bigint | null, activeDurationMs: bigint | null, tokensPerSecond: number | null, };
